
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALBERTO
 */
public class ValorVenta extends javax.swing.JFrame  implements ActionListener{

   MenuPrincipal menuprincipal=new MenuPrincipal();
  PrecioVenta precioventa=new PrecioVenta();
   sssss ssssss=new sssss();
   
   
    public ValorVenta() {
        initComponents();
       Contendor.add(ssssss);
       
       ssssss.setVisible(true);
       precioventa.setVisible(false);
        btnanterior.addActionListener(this);
        btnsiguiente.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contendor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnanterior = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contendor.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnanterior.setText("Anterior");
        jPanel1.add(btnanterior);

        btnsiguiente.setText("Siguiente");
        jPanel1.add(btnsiguiente);

        jButton1.setText("Limpiar");
        jPanel1.add(jButton1);

        Contendor.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Contendor, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValorVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValorVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValorVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValorVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValorVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contendor;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt =ae.getSource();
        if(evt.equals(btnanterior)){
        ssssss.setVisible(false);
         precioventa.setVisible(true);
         
          Contendor.add(ssssss);
          Contendor.validate();
        }else if(evt.equals(btnsiguiente)){
        precioventa.setVisible(false);
        ssssss.setVisible(true);
         
          Contendor.add(ssssss);
          Contendor.validate();
        }
        
    }
}
